// Code generated by protoc-gen-go. DO NOT EDIT.
// source: platform/user_srv_passport.proto

package passport

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	base "github.com/tinyhole/user-srv-passport/idl/base"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Code int32

const (
	Code_Ok                        Code = 0
	Code_Failed                    Code = 1
	Code_MobileAlreadySignedUp     Code = 2
	Code_MobileNotSignedUp         Code = 3
	Code_IncorrectMobileOrPassword Code = 4
)

var Code_name = map[int32]string{
	0: "Ok",
	1: "Failed",
	2: "MobileAlreadySignedUp",
	3: "MobileNotSignedUp",
	4: "IncorrectMobileOrPassword",
}

var Code_value = map[string]int32{
	"Ok":                        0,
	"Failed":                    1,
	"MobileAlreadySignedUp":     2,
	"MobileNotSignedUp":         3,
	"IncorrectMobileOrPassword": 4,
}

func (x Code) String() string {
	return proto.EnumName(Code_name, int32(x))
}

func (Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d68c7dc98409413c, []int{0}
}

type BaseRsp struct {
	Code                 Code     `protobuf:"varint,1,opt,name=code,proto3,enum=platform.user.srv.passport.Code" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseRsp) Reset()         { *m = BaseRsp{} }
func (m *BaseRsp) String() string { return proto.CompactTextString(m) }
func (*BaseRsp) ProtoMessage()    {}
func (*BaseRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d68c7dc98409413c, []int{0}
}

func (m *BaseRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseRsp.Unmarshal(m, b)
}
func (m *BaseRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseRsp.Marshal(b, m, deterministic)
}
func (m *BaseRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseRsp.Merge(m, src)
}
func (m *BaseRsp) XXX_Size() int {
	return xxx_messageInfo_BaseRsp.Size(m)
}
func (m *BaseRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseRsp.DiscardUnknown(m)
}

var xxx_messageInfo_BaseRsp proto.InternalMessageInfo

func (m *BaseRsp) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_Ok
}

func (m *BaseRsp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type SignUpReq struct {
	DeviceID             int64           `protobuf:"varint,1,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"`
	Name                 string          `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Mobile               string          `protobuf:"bytes,3,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Email                string          `protobuf:"bytes,4,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string          `protobuf:"bytes,5,opt,name=Password,proto3" json:"Password,omitempty"`
	Code                 string          `protobuf:"bytes,6,opt,name=Code,proto3" json:"Code,omitempty"`
	ActiveType           base.ActiveType `protobuf:"varint,7,opt,name=ActiveType,proto3,enum=base.ActiveType" json:"ActiveType,omitempty"`
	AppID                int32           `protobuf:"varint,8,opt,name=AppID,proto3" json:"AppID,omitempty"`
	Version              string          `protobuf:"bytes,9,opt,name=Version,proto3" json:"Version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SignUpReq) Reset()         { *m = SignUpReq{} }
func (m *SignUpReq) String() string { return proto.CompactTextString(m) }
func (*SignUpReq) ProtoMessage()    {}
func (*SignUpReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d68c7dc98409413c, []int{1}
}

func (m *SignUpReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpReq.Unmarshal(m, b)
}
func (m *SignUpReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpReq.Marshal(b, m, deterministic)
}
func (m *SignUpReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpReq.Merge(m, src)
}
func (m *SignUpReq) XXX_Size() int {
	return xxx_messageInfo_SignUpReq.Size(m)
}
func (m *SignUpReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpReq proto.InternalMessageInfo

func (m *SignUpReq) GetDeviceID() int64 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *SignUpReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SignUpReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *SignUpReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignUpReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SignUpReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *SignUpReq) GetActiveType() base.ActiveType {
	if m != nil {
		return m.ActiveType
	}
	return base.ActiveType_ActiveTypeEmail
}

func (m *SignUpReq) GetAppID() int32 {
	if m != nil {
		return m.AppID
	}
	return 0
}

func (m *SignUpReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type SignUpRsp struct {
	UserID               int64    `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	BaseRsp              *BaseRsp `protobuf:"bytes,3,opt,name=BaseRsp,proto3" json:"BaseRsp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRsp) Reset()         { *m = SignUpRsp{} }
func (m *SignUpRsp) String() string { return proto.CompactTextString(m) }
func (*SignUpRsp) ProtoMessage()    {}
func (*SignUpRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d68c7dc98409413c, []int{2}
}

func (m *SignUpRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRsp.Unmarshal(m, b)
}
func (m *SignUpRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRsp.Marshal(b, m, deterministic)
}
func (m *SignUpRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRsp.Merge(m, src)
}
func (m *SignUpRsp) XXX_Size() int {
	return xxx_messageInfo_SignUpRsp.Size(m)
}
func (m *SignUpRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRsp proto.InternalMessageInfo

func (m *SignUpRsp) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *SignUpRsp) GetBaseRsp() *BaseRsp {
	if m != nil {
		return m.BaseRsp
	}
	return nil
}

type WeChatSignInReq struct {
	DeviceID             int64    `protobuf:"varint,1,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`
	AppID                string   `protobuf:"bytes,3,opt,name=AppID,proto3" json:"AppID,omitempty"`
	Secret               string   `protobuf:"bytes,4,opt,name=Secret,proto3" json:"Secret,omitempty"`
	ExtraInfo            string   `protobuf:"bytes,5,opt,name=ExtraInfo,proto3" json:"ExtraInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WeChatSignInReq) Reset()         { *m = WeChatSignInReq{} }
func (m *WeChatSignInReq) String() string { return proto.CompactTextString(m) }
func (*WeChatSignInReq) ProtoMessage()    {}
func (*WeChatSignInReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d68c7dc98409413c, []int{3}
}

func (m *WeChatSignInReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeChatSignInReq.Unmarshal(m, b)
}
func (m *WeChatSignInReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeChatSignInReq.Marshal(b, m, deterministic)
}
func (m *WeChatSignInReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeChatSignInReq.Merge(m, src)
}
func (m *WeChatSignInReq) XXX_Size() int {
	return xxx_messageInfo_WeChatSignInReq.Size(m)
}
func (m *WeChatSignInReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WeChatSignInReq.DiscardUnknown(m)
}

var xxx_messageInfo_WeChatSignInReq proto.InternalMessageInfo

func (m *WeChatSignInReq) GetDeviceID() int64 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *WeChatSignInReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *WeChatSignInReq) GetAppID() string {
	if m != nil {
		return m.AppID
	}
	return ""
}

func (m *WeChatSignInReq) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *WeChatSignInReq) GetExtraInfo() string {
	if m != nil {
		return m.ExtraInfo
	}
	return ""
}

type WeChatSignInRsp struct {
	UserID               int64    `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	IsFirstSignIn        bool     `protobuf:"varint,2,opt,name=IsFirstSignIn,proto3" json:"IsFirstSignIn,omitempty"`
	BaseRsp              *BaseRsp `protobuf:"bytes,3,opt,name=BaseRsp,proto3" json:"BaseRsp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WeChatSignInRsp) Reset()         { *m = WeChatSignInRsp{} }
func (m *WeChatSignInRsp) String() string { return proto.CompactTextString(m) }
func (*WeChatSignInRsp) ProtoMessage()    {}
func (*WeChatSignInRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d68c7dc98409413c, []int{4}
}

func (m *WeChatSignInRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeChatSignInRsp.Unmarshal(m, b)
}
func (m *WeChatSignInRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeChatSignInRsp.Marshal(b, m, deterministic)
}
func (m *WeChatSignInRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeChatSignInRsp.Merge(m, src)
}
func (m *WeChatSignInRsp) XXX_Size() int {
	return xxx_messageInfo_WeChatSignInRsp.Size(m)
}
func (m *WeChatSignInRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_WeChatSignInRsp.DiscardUnknown(m)
}

var xxx_messageInfo_WeChatSignInRsp proto.InternalMessageInfo

func (m *WeChatSignInRsp) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *WeChatSignInRsp) GetIsFirstSignIn() bool {
	if m != nil {
		return m.IsFirstSignIn
	}
	return false
}

func (m *WeChatSignInRsp) GetBaseRsp() *BaseRsp {
	if m != nil {
		return m.BaseRsp
	}
	return nil
}

type MobileSignInReq struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	AppID                int32    `protobuf:"varint,3,opt,name=AppID,proto3" json:"AppID,omitempty"`
	ExtraInfo            string   `protobuf:"bytes,4,opt,name=ExtraInfo,proto3" json:"ExtraInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MobileSignInReq) Reset()         { *m = MobileSignInReq{} }
func (m *MobileSignInReq) String() string { return proto.CompactTextString(m) }
func (*MobileSignInReq) ProtoMessage()    {}
func (*MobileSignInReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d68c7dc98409413c, []int{5}
}

func (m *MobileSignInReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MobileSignInReq.Unmarshal(m, b)
}
func (m *MobileSignInReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MobileSignInReq.Marshal(b, m, deterministic)
}
func (m *MobileSignInReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MobileSignInReq.Merge(m, src)
}
func (m *MobileSignInReq) XXX_Size() int {
	return xxx_messageInfo_MobileSignInReq.Size(m)
}
func (m *MobileSignInReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MobileSignInReq.DiscardUnknown(m)
}

var xxx_messageInfo_MobileSignInReq proto.InternalMessageInfo

func (m *MobileSignInReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *MobileSignInReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *MobileSignInReq) GetAppID() int32 {
	if m != nil {
		return m.AppID
	}
	return 0
}

func (m *MobileSignInReq) GetExtraInfo() string {
	if m != nil {
		return m.ExtraInfo
	}
	return ""
}

type MobileSignInRsp struct {
	UserID               int64    `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	BaseRsp              *BaseRsp `protobuf:"bytes,2,opt,name=BaseRsp,proto3" json:"BaseRsp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MobileSignInRsp) Reset()         { *m = MobileSignInRsp{} }
func (m *MobileSignInRsp) String() string { return proto.CompactTextString(m) }
func (*MobileSignInRsp) ProtoMessage()    {}
func (*MobileSignInRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d68c7dc98409413c, []int{6}
}

func (m *MobileSignInRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MobileSignInRsp.Unmarshal(m, b)
}
func (m *MobileSignInRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MobileSignInRsp.Marshal(b, m, deterministic)
}
func (m *MobileSignInRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MobileSignInRsp.Merge(m, src)
}
func (m *MobileSignInRsp) XXX_Size() int {
	return xxx_messageInfo_MobileSignInRsp.Size(m)
}
func (m *MobileSignInRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_MobileSignInRsp.DiscardUnknown(m)
}

var xxx_messageInfo_MobileSignInRsp proto.InternalMessageInfo

func (m *MobileSignInRsp) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *MobileSignInRsp) GetBaseRsp() *BaseRsp {
	if m != nil {
		return m.BaseRsp
	}
	return nil
}

func init() {
	proto.RegisterEnum("platform.user.srv.passport.Code", Code_name, Code_value)
	proto.RegisterType((*BaseRsp)(nil), "platform.user.srv.passport.BaseRsp")
	proto.RegisterType((*SignUpReq)(nil), "platform.user.srv.passport.SignUpReq")
	proto.RegisterType((*SignUpRsp)(nil), "platform.user.srv.passport.SignUpRsp")
	proto.RegisterType((*WeChatSignInReq)(nil), "platform.user.srv.passport.WeChatSignInReq")
	proto.RegisterType((*WeChatSignInRsp)(nil), "platform.user.srv.passport.WeChatSignInRsp")
	proto.RegisterType((*MobileSignInReq)(nil), "platform.user.srv.passport.MobileSignInReq")
	proto.RegisterType((*MobileSignInRsp)(nil), "platform.user.srv.passport.MobileSignInRsp")
}

func init() { proto.RegisterFile("platform/user_srv_passport.proto", fileDescriptor_d68c7dc98409413c) }

var fileDescriptor_d68c7dc98409413c = []byte{
	// 573 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x25, 0x69, 0x9b, 0xb6, 0x97, 0x8f, 0x06, 0x8b, 0x4d, 0x59, 0x34, 0xa4, 0xaa, 0x80, 0x54,
	0x81, 0x94, 0xa2, 0xc2, 0x2b, 0x0f, 0xdd, 0xba, 0x49, 0x79, 0x60, 0x83, 0x8c, 0x0e, 0x89, 0x97,
	0x29, 0x4d, 0xee, 0xd6, 0x68, 0x6d, 0x6d, 0xec, 0x50, 0xe8, 0x8f, 0x80, 0x9f, 0xc3, 0x9f, 0xe3,
	0x05, 0xd9, 0x4e, 0xd2, 0x36, 0x12, 0x55, 0xd1, 0x5e, 0x22, 0xdf, 0xeb, 0xe3, 0x7b, 0xef, 0x39,
	0x3e, 0x31, 0xb4, 0xd9, 0x34, 0x4c, 0xaf, 0x29, 0x9f, 0xf5, 0xbe, 0x09, 0xe4, 0x57, 0x82, 0x2f,
	0xae, 0x58, 0x28, 0x04, 0xa3, 0x3c, 0xf5, 0x18, 0xa7, 0x29, 0x25, 0x6e, 0x8e, 0xf0, 0x24, 0xc2,
	0x13, 0x7c, 0xe1, 0xe5, 0x08, 0xb7, 0x35, 0x0e, 0x05, 0xf6, 0xe4, 0x47, 0x83, 0x3b, 0x1f, 0xa1,
	0x7e, 0x14, 0x0a, 0x0c, 0x04, 0x23, 0x6f, 0xa1, 0x1a, 0xd1, 0x18, 0x1d, 0xa3, 0x6d, 0x74, 0x1f,
	0xf5, 0xdb, 0xde, 0xbf, 0xcb, 0x78, 0xc7, 0x34, 0xc6, 0x40, 0xa1, 0x89, 0x0d, 0x95, 0x99, 0xb8,
	0x71, 0xcc, 0xb6, 0xd1, 0x6d, 0x06, 0x72, 0xd9, 0xf9, 0x63, 0x40, 0xf3, 0x22, 0xb9, 0x99, 0x8f,
	0x58, 0x80, 0x5f, 0x89, 0x0b, 0x8d, 0x21, 0x2e, 0x92, 0x08, 0xfd, 0xa1, 0xaa, 0x5c, 0x09, 0x8a,
	0x98, 0x10, 0xa8, 0x9e, 0x85, 0x33, 0xcc, 0x0e, 0xab, 0x35, 0xd9, 0x07, 0xeb, 0x3d, 0x1d, 0x27,
	0x53, 0x74, 0x2a, 0x2a, 0x9b, 0x45, 0xe4, 0x09, 0xd4, 0x4e, 0x66, 0x61, 0x32, 0x75, 0xaa, 0x2a,
	0xad, 0x03, 0x59, 0xfd, 0x43, 0x28, 0xc4, 0x77, 0xca, 0x63, 0xa7, 0xa6, 0x36, 0x8a, 0x58, 0x56,
	0x97, 0x73, 0x3a, 0x96, 0xae, 0x2e, 0xd7, 0xe4, 0x35, 0xc0, 0x20, 0x4a, 0x93, 0x05, 0x7e, 0x5a,
	0x32, 0x74, 0xea, 0x8a, 0xa9, 0xed, 0x29, 0x3d, 0x56, 0xf9, 0x60, 0x0d, 0x23, 0xfb, 0x0e, 0x18,
	0xf3, 0x87, 0x4e, 0xa3, 0x6d, 0x74, 0x6b, 0x81, 0x0e, 0x88, 0x03, 0xf5, 0x4b, 0xe4, 0x22, 0xa1,
	0x73, 0xa7, 0xa9, 0xca, 0xe7, 0x61, 0x67, 0x5c, 0x90, 0x17, 0x4c, 0x92, 0x19, 0x09, 0xe4, 0x05,
	0xf5, 0x2c, 0x22, 0xef, 0x0a, 0xd5, 0x15, 0xcb, 0xfb, 0xfd, 0x67, 0xdb, 0xd4, 0xce, 0xa0, 0x41,
	0x7e, 0xa6, 0xf3, 0xd3, 0x80, 0xd6, 0x67, 0x3c, 0x9e, 0x84, 0xa9, 0x6c, 0xe5, 0xcf, 0x77, 0xd0,
	0x59, 0x29, 0x61, 0xae, 0x29, 0x51, 0xf0, 0xd2, 0x32, 0x67, 0xbc, 0xf6, 0xc1, 0xba, 0xc0, 0x88,
	0x63, 0x9a, 0xc9, 0x9c, 0x45, 0xe4, 0x10, 0x9a, 0x27, 0x3f, 0x52, 0x1e, 0xfa, 0xf3, 0x6b, 0x9a,
	0x09, 0xbd, 0x4a, 0x74, 0x7e, 0x95, 0xe7, 0xd9, 0x42, 0xfd, 0x39, 0x3c, 0xf4, 0xc5, 0x69, 0xc2,
	0x45, 0x86, 0x55, 0x43, 0x35, 0x82, 0xcd, 0xe4, 0x5d, 0x05, 0x5a, 0x42, 0x4b, 0xdb, 0x66, 0xa5,
	0xcf, 0xca, 0x57, 0xc6, 0x86, 0xaf, 0xd6, 0x1d, 0x64, 0x96, 0x1c, 0xb4, 0xa1, 0x51, 0x71, 0xf7,
	0x1b, 0x5a, 0x54, 0xcb, 0x5a, 0x4c, 0x4a, 0xad, 0x77, 0x73, 0x81, 0xf9, 0xff, 0x24, 0x5f, 0xde,
	0xea, 0x5b, 0x25, 0x16, 0x98, 0xe7, 0xb7, 0xf6, 0x3d, 0x02, 0x60, 0x9d, 0x86, 0xc9, 0x14, 0x63,
	0xdb, 0x20, 0x07, 0xb0, 0xa7, 0xa7, 0x18, 0x4c, 0x39, 0x86, 0xf1, 0x52, 0x0e, 0x83, 0xf1, 0x88,
	0xd9, 0x26, 0xd9, 0x83, 0xc7, 0x7a, 0xeb, 0x8c, 0xa6, 0x45, 0xba, 0x42, 0x9e, 0xc2, 0x81, 0x3f,
	0x8f, 0x28, 0xe7, 0x18, 0xa5, 0x7a, 0xff, 0x9c, 0xe7, 0x42, 0xd8, 0xd5, 0xfe, 0x6f, 0x53, 0xeb,
	0x24, 0x47, 0x21, 0x97, 0x60, 0x69, 0x8f, 0x93, 0x17, 0xdb, 0x26, 0x2e, 0x1e, 0x01, 0x77, 0x17,
	0x98, 0x60, 0x64, 0x02, 0x0f, 0xd6, 0x6d, 0x44, 0x5e, 0x6d, 0x3b, 0x56, 0xfa, 0x01, 0xdc, 0xdd,
	0xc1, 0xba, 0xd3, 0xfa, 0x2d, 0x6d, 0xef, 0x54, 0xb2, 0x92, 0xbb, 0x3b, 0x58, 0xb0, 0xa3, 0xc3,
	0x2f, 0xee, 0xc6, 0x8b, 0xdd, 0x13, 0x7c, 0xd1, 0xcb, 0xd1, 0x63, 0x4b, 0xbd, 0xc2, 0x6f, 0xfe,
	0x06, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xa8, 0x8e, 0x49, 0xd6, 0x05, 0x00, 0x00,
}
